### ISSUE TITLE
Configure failure

### ISSUE THREAD

**Issue by zinid** [processone/epam#6]
Configure fails with the latest [HEAD](bc4681599be65802fd1cab65515acbc9b3afa0e7):
```
$ ./configure
...
config.status: error: cannot find input file: `vars.config.in'
```

Also, it seems like the application was renamed, but old name is still found in the sources:
```
$ grep 'p1_pam' -rH .
./src/epam.erl:     case code:priv_dir(p1_pam) of
```

**Comment by prefiks** [comment]
I added vars.config.in in 91967e715b47e26e25ff36752b0f8b3aa15b3922

**Comment by prefiks** [comment]
And that other one in aab4c766682f226efae342f22122f6bc0b47132a

**Comment by zinid** [comment]
Thanks, I close the ticket ;)
